### ISSUE TITLE
Test suite fails but everything is ok

### ISSUE THREAD

**Issue by lautaropaske** [tomasiturralde/bibliotecame-back#7]
When we run the complete test suite, one test fails:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/22356822/91741471-24e21800-eb8b-11ea-9d2c-581fc781189e.png">

When we run that test on its own, it passes. This is because when we run the whole suite, by the time the `void testAddBook()` test is ran we encounter that the book we expect (`line 104`) to be new is already created.

There are many ways to avoid these situations. I'm opening this as an issue on itself and not blocking PRs because it's not a big deal now but we should fix this in the short-term as our test suite should reflect real errors if any. Otherwise, we'll start to ignore it which is not cool.

**Comment by FacundoBocalandro** [comment]
Should we add the deletion of the recently created book after each test? By that means, leaving the database in the same state as it was found in.

**Comment by lautaropaske** [comment]
@FacundoBocalandro That could be a possible solution. You could also randomize the name of the resources created if appropiate (e.g `Las mariasA9H!HAXMNUWP#`)

**Comment by lautaropaske** [comment]
Due to recent merges, these tests are also fit for necessary refactoring related to this issue:

- bibliotecame.back.UserTests.testUnauthorizedOnTryingToModifyAnIdDifferentFromMyId(),
- bibliotecame.back.BookTests.testAddBook(), 
- bibliotecame.back.UserTests.testDeleteUser(), 
- bibliotecame.back.UserTests.testUnauthorizedWhenUpdatingBodyUserIdDiffersFromLoggedId(), 
- bibliotecame.back.UserTests.testUnauthorizedWhenUsingUpdateForChangingEmail(), 
- bibliotecame.back.UserTests.testBadRequestWhenTryingToUpdateUserWithInvalidPassword()
